In [3]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
import numpy as np

In [4]:
df=pd.read_csv("tel_churn.csv")
df.head()

Unnamed: 0  SeniorCitizen  MonthlyCharges  TotalCharges  Churn  \
0           0              0           29.85         29.85      0   
1           1              0           56.95       1889.50      0   
2           2              0           53.85        108.15      1   
3           3              0           42.30       1840.75      0   
4           4              0           70.70        151.65      1   

   gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  ...  \
0           True        False       False         True           True  ...   
1          False         True        True        False           True  ...   
2          False         True        True        False           True  ...   
3          False         True        True        False           True  ...   
4           True        False        True        False           True  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                    False   
1                                    False   
2                                    False   
3                                     True   
4                                    False   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True   
1                                  False                           False   
2                                  False                           False   
3                                  False                           False   
4                                  False                            True   

   PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                       False                 True                 False   
1                        True                False                 False   
2                        True                 True                 False   
3                       False                False                 False   
4                       False                 True                 False   

   tenure_group_25 - 36  tenure_group_37 - 48  tenure_group_49 - 60  \
0                 False                 False                 False   
1                  True                 False                 False   
2                 False                 False                 False   
3                 False                  True                 False   
4                 False                 False                 False   

   tenure_group_61 - 72  
0                 False  
1                 False  
2                 False  
3                 False  
4                 False  

[5 rows x 52 columns]

In [5]:
df=df.drop('Unnamed: 0',axis=1)

In [6]:
x=df.drop('Churn',axis=1)
x

SeniorCitizen  MonthlyCharges  TotalCharges  gender_Female  gender_Male  \
0                 0           29.85         29.85           True        False   
1                 0           56.95       1889.50          False         True   
2                 0           53.85        108.15          False         True   
3                 0           42.30       1840.75          False         True   
4                 0           70.70        151.65           True        False   
...             ...             ...           ...            ...          ...   
7027              0           84.80       1990.50          False         True   
7028              0          103.20       7362.90           True        False   
7029              0           29.60        346.45           True        False   
7030              1           74.40        306.60          False         True   
7031              0          105.65       6844.50          False         True   

      Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  PhoneService_No  \
0          False         True           True           False             True   
1           True        False           True           False            False   
2           True        False           True           False            False   
3           True        False           True           False             True   
4           True        False           True           False            False   
...          ...          ...            ...             ...              ...   
7027       False         True          False            True            False   
7028       False         True          False            True            False   
7029       False         True          False            True             True   
7030       False         True           True           False            False   
7031        True        False           True           False            False   

      ...  PaymentMethod_Bank transfer (automatic)  \
0     ...                                    False   
1     ...                                    False   
2     ...                                    False   
3     ...                                     True   
4     ...                                    False   
...   ...                                      ...   
7027  ...                                    False   
7028  ...                                    False   
7029  ...                                    False   
7030  ...                                    False   
7031  ...                                     True   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                     False                            True   
1                                     False                           False   
2                                     False                           False   
3                                     False                           False   
4                                     False                            True   
...                                     ...                             ...   
7027                                  False                           False   
7028                                   True                           False   
7029                                  False                            True   
7030                                  False                           False   
7031                                  False                           False   

      PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                          False                 True                 False   
1                           True                False                 False   
2                           True                 True                 False   
3                          False                False                 False   
4                          False                 True              

In [7]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

### Decision Tree Classifier

In [9]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [10]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [11]:
y_pred=model_dt.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 1, 0], dtype=int64)

In [12]:
model_dt.score(x_test,y_test)

0.7860696517412935

In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.87      0.85      1019
           1       0.62      0.57      0.60       388

    accuracy                           0.79      1407
   macro avg       0.73      0.72      0.73      1407
weighted avg       0.78      0.79      0.78      1407



In [14]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)

In [15]:
xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)

In [16]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [17]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9433797909407665
              precision    recall  f1-score   support

           0       0.96      0.91      0.93       511
           1       0.93      0.97      0.95       637

    accuracy                           0.94      1148
   macro avg       0.95      0.94      0.94      1148
weighted avg       0.94      0.94      0.94      1148



In [18]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[467  44]
 [ 21 616]]


### Random Forest Classifier

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
model_rf=RandomForestClassifier(n_estimators=10, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [21]:

model_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, n_estimators=10,
                       random_state=100)

In [22]:
y_pred=model_rf.predict(x_test)

In [23]:
model_rf.score(x_test,y_test)

0.8017057569296375

In [24]:
print(classification_report(y_test, y_pred, ))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1019
           1       0.69      0.51      0.58       388

    accuracy                           0.80      1407
   macro avg       0.76      0.71      0.73      1407
weighted avg       0.79      0.80      0.79      1407



In [25]:

sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

In [26]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [27]:
model_rf_smote=RandomForestClassifier(criterion='entropy', max_depth= 12, min_samples_leaf= 4 ,n_estimators= 200, random_state= 100)

In [28]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(criterion='entropy', max_depth=12, min_samples_leaf=4,
                       n_estimators=200, random_state=100)

In [29]:

yr_predict1 = model_rf_smote.predict(xr_test1)

In [30]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [31]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.9580479452054794
              precision    recall  f1-score   support

           0       0.97      0.94      0.95       544
           1       0.95      0.98      0.96       624

    accuracy                           0.96      1168
   macro avg       0.96      0.96      0.96      1168
weighted avg       0.96      0.96      0.96      1168



In [32]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))

[[510  34]
 [ 15 609]]


In [31]:
from sklearn.model_selection import GridSearchCV

In [33]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [50,100, 200],
    'max_depth': [6, 8, 10, 12],
    'random_state' : [50,100,150],
    'min_samples_leaf': [4, 8, 12],
    'criterion': ['gini', 'entropy']
}

# Initialize GridSearchCV with the RandomForest model
grid_search = GridSearchCV(estimator=model_rf_smote,
                           param_grid=param_grid,
                           cv=5,
                           scoring='accuracy',
                           n_jobs=-1,
                           verbose=2)

# Fit the grid search to the resampled training data
grid_search.fit(X_resampled1, y_resampled1)

# Retrieve and print the best parameters found by grid search
best_params = grid_search.best_params_
print("Best parameters found: ", best_params)


Fitting 5 folds for each of 216 candidates, totalling 1080 fits


C:\Users\abuba\anaconda3\Lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


Best parameters found:  {'criterion': 'entropy', 'max_depth': 12, 'min_samples_leaf': 4, 'n_estimators': 200, 'random_state': 100}


### Performing PCA

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

In [ ]:
model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [ ]:

model.fit(xr_train_pca,yr_train1)

In [ ]:
yr_predict_pca = model.predict(xr_test_pca)

In [ ]:
model_score_r_pca = model.score(xr_test_pca, yr_test1)

In [ ]:
print(model_score_r_pca)
print(metrics.classification_report(yr_test1, yr_predict_pca))

In [37]:
input_data = [
    [0, 70.70, 151.65, "Female", "No", "No", "Yes", "No", "Fiber optic", "No", "Yes", "No", "No", "No", "No", "Month-to-Month", "yes","Electronic check", 2]
]

input_df = pd.DataFrame(input_data, columns=[
    'Column1', 'Column2', 'Column3', 'Column4', 'Column5', 
    'Column6', 'Column7', 'Column8', 'Column9', 'Column10', 
    'Column11', 'Column12', 'Column13', 'Column14', 'Column15', 
    'Column16', 'Column17', 'Column18'])


ValueError: 18 columns passed, passed data had 19 columns

In [38]:
model_columns = list(xr_train1.columns)
encoded_input = input_df.reindex(columns=model_columns, fill_value=0)


In [ ]:
# Convert the DataFrame to a NumPy array if needed by the model
encoded_input_array = encoded_input.to_numpy()

# Predict using the pre-trained model
predicted_value = model_rf_smote.predict(encoded_input_array)

print(predicted_value)

In [41]:

import pickle

In [42]:
filename = 'model.sav'

In [43]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [44]:
load_model = pickle.load(open(filename, 'rb'))

In [45]:
model_score_r1 = load_model.score(xr_test1, yr_test1)

In [46]:

model_score_r1


0.9464131374243734

In [48]:
  # X_train is your training data
model_columns = list(xr_train1.columns)
pickle.dump(model_columns, open("model_columns.pkl", "wb"))
